# --- Ports ---
listeners.tcp.default = 5672
management.tcp.port   = 15672

# --- Accès / sécurité ---
loopback_users.guest = false

# CORS Management UI / API (⚠️ origins explicites si credentials=true)
# Duplique la ligne allow_origins.N si tu as plusieurs domaines.
management.cors.allow_origins.1 = https://apis-dev.roomee.io
management.cors.allow_origins.2 = https://apis-staging.roomee.io
management.cors.allow_origins.3 = https://apis-prod.roomee.io

# management.cors.credentials = true

# Cache du preflight (en secondes)
management.cors.max_age = 3600

# --- Mémoire ---
vm_memory_high_watermark.relative = 0.6

# --- Logging ---
log.console = true
log.console.level = info

# --- Heartbeat ---
heartbeat = 60

# --- Valeurs par défaut (si l'état n'est pas déjà persisté par un volume) ---
default_vhost = /
default_user_tags.administrator = true
default_permissions.configure = .*
default_permissions.read      = .*
default_permissions.write     = .*

# --- Charger automatiquement les définitions au démarrage ---
load_definitions = /etc/rabbitmq/definitions.json

