# --- Ports ---
listeners.tcp.default = 5672
management.tcp.port   = 15672
management.tcp.ip     = 0.0.0.0

## --- Servir la console sous /amqp ---
# management.path_prefix = /amqp
# (facultatif) rediriger automatiquement / -> /amqp
# management.redirect_to_management = true   # selon version, parfois nommé management.redirect_to_prefixed


# --- Accès ---
loopback_users.guest = false

# --- CORS (déclare tes origines en prod) ---
# Exemple local (remplace par ton domaine en prod) :
management.cors.allow_origins.1 = https://apis-dev.roomee.io
management.cors.allow_origins.2 = https://apis-staging.roomee.io
management.cors.allow_origins.3 = https://apis-prod.roomee.io
management.cors.allow_origins.3 = https://amqp.roomee.io
management.cors.max_age         = 3600

# --- Mémoire ---
vm_memory_high_watermark.relative = 0.6

# --- Logging ---
log.console = true
log.console.level = info

# --- Heartbeat ---
heartbeat = 60

# --- Valeurs par défaut (si pas déjà persistées) ---
default_vhost = /
default_user_tags.administrator = true
default_permissions.configure = .*
default_permissions.read      = .*
default_permissions.write     = .*

# --- Charger les définitions ---
# (clé moderne ; évite l’ancienne management.load_definitions)
load_definitions = /etc/rabbitmq/definitions.json

# (optionnel recommandé) Arrêt en cas de disque trop bas :
# disk_free_limit.absolute = 500MB

